apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  #annotations:
  #  networking.gke.io/v1beta1.FrontendConfig: "wordpress"
spec:
  #tls:
  #- secretName: wordpress-ssl
  defaultBackend:
    service:
      name: wordpress
      port:
        number: 80
